### ISSUE TITLE
☁️ Cloud Deployment Options - One-Click Cloud Hosting

### ISSUE THREAD

**Issue by timmybird** [PitchConnect/fogis-deployment#8]
## 🎯 Goal
Provide one-click cloud deployment options for FOGIS, enabling users to deploy and manage FOGIS systems in the cloud without local infrastructure requirements.

## 📋 Current State
Users must:
- Set up local Docker environment
- Manage local infrastructure and resources
- Handle system maintenance and updates manually
- Ensure local system availability and reliability
- Deal with network configuration and port management

## 🚀 Desired State
```bash
# One-click cloud deployment
./deploy_to_cloud.sh --provider=aws --region=us-east-1
# OR
# Web-based deployment wizard
https://deploy.fogis.io -> Click "Deploy to AWS" -> System running in 5 minutes
```

### Cloud Provider Support
- [ ] **AWS Deployment** - ECS/Fargate containerized deployment
- [ ] **Google Cloud** - Cloud Run serverless deployment
- [ ] **Azure** - Container Instances deployment
- [ ] **DigitalOcean** - App Platform deployment
- [ ] **Heroku** - Container-based deployment
- [ ] **Railway** - Simple container deployment

### Deployment Methods
- [ ] **Infrastructure as Code** - Terraform templates for each provider
- [ ] **One-Click Deploy** - Pre-configured deployment buttons
- [ ] **CLI Deployment** - Command-line deployment tools
- [ ] **Web Wizard** - Browser-based deployment interface
- [ ] **GitHub Actions** - Automated deployment from repository
- [ ] **Docker Compose Cloud** - Cloud-native compose deployments

### Cloud-Native Features
- [ ] **Auto-Scaling** - Automatic scaling based on load
- [ ] **Load Balancing** - Distribute traffic across instances
- [ ] **Managed Databases** - Cloud database integration
- [ ] **Secret Management** - Cloud-native credential storage
- [ ] **Monitoring Integration** - Cloud provider monitoring
- [ ] **Backup Solutions** - Automated cloud backups

### Cost Management
- [ ] **Cost Estimation** - Pre-deployment cost calculator
- [ ] **Resource Optimization** - Right-sizing recommendations
- [ ] **Auto-Shutdown** - Schedule-based resource management
- [ ] **Spot Instances** - Cost-effective compute options
- [ ] **Reserved Capacity** - Long-term cost optimization
- [ ] **Budget Alerts** - Cost monitoring and alerts

### Phase 1: AWS Deployment
```yaml
# terraform/aws/main.tf
provider "aws" {
  region = var.aws_region
}

# ECS Cluster
resource "aws_ecs_cluster" "fogis_cluster" {
  name = "fogis-${var.environment}"
  
  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}

# Application Load Balancer
resource "aws_lb" "fogis_alb" {
  name               = "fogis-alb"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.alb.id]
  subnets           = aws_subnet.public[*].id
}

# ECS Service for each FOGIS component
resource "aws_ecs_service" "fogis_api_client" {
  name            = "fogis-api-client"
  cluster         = aws_ecs_cluster.fogis_cluster.id
  task_definition = aws_ecs_task_definition.fogis_api_client.arn
  desired_count   = var.api_client_replicas
  
  deployment_configuration {
    maximum_percent         = 200
    minimum_healthy_percent = 100
  }
  
  load_balancer {
    target_group_arn = aws_lb_target_group.api_client.arn
    container_name   = "fogis-api-client"
    container_port   = 8080
  }
}

# RDS for persistent data
resource "aws_db_instance" "fogis_db" {
  identifier = "fogis-database"
  engine     = "postgres"
  engine_version = "13.7"
  instance_class = "db.t3.micro"
  allocated_storage = 20
  
  db_name  = "fogis"
  username = var.db_username
  password = var.db_password
  
  backup_retention_period = 7
  backup_window          = "03:00-04:00"
  maintenance_window     = "sun:04:00-sun:05:00"
  
  skip_final_snapshot = true
}
```

### Phase 2: Multi-Cloud Support
```yaml
# terraform/gcp/main.tf
provider "google" {
  project = var.gcp_project
  region  = var.gcp_region
}

# Cloud Run services
resource "google_cloud_run_service" "fogis_api_client" {
  name     = "fogis-api-client"
  location = var.gcp_region
  
  template {
    spec {
      containers {
        image = "gcr.io/${var.gcp_project}/fogis-api-client:latest"
        
        env {
          name  = "DATABASE_URL"
          value = google_sql_database_instance.fogis_db.connection_name
        }
        
        resources {
          limits = {
            cpu    = "1000m"
            memory = "512Mi"
          }
        }
      }
      
      container_concurrency = 100
    }
    
    metadata {
      annotations = {
        "autoscaling.knative.dev/maxScale" = "10"
        "autoscaling.knative.dev/minScale" = "1"
      }
    }
  }
  
  traffic {
    percent         = 100
    latest_revision = true
  }
}

# Cloud SQL instance
resource "google_sql_database_instance" "fogis_db" {
  name             = "fogis-db-${random_id.db_name_suffix.hex}"
  database_version = "POSTGRES_13"
  region          = var.gcp_region
  
  settings {
    tier = "db-f1-micro"
    
    backup_configuration {
      enabled    = true
      start_time = "03:00"
    }
    
    ip_configuration {
      ipv4_enabled = true
      authorized_networks {
        value = "0.0.0.0/0"
      }
    }
  }
}
```

### Phase 3: Deployment Automation
```yaml
# .github/workflows/deploy-cloud.yml
name: Deploy to Cloud

on:
  workflow_dispatch:
    inputs:
      provider:
        description: 'Cloud provider'
        required: true
        default: 'aws'
        type: choice
        options:
          - aws
          - gcp
          - azure
      environment:
        description: 'Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      
      - name: Configure AWS credentials
        if: github.event.inputs.provider == 'aws'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy to AWS
        if: github.event.inputs.provider == 'aws'
        run: |
          cd terraform/aws
          terraform init
          terraform plan -var="environment=${{ github.event.inputs.environment }}"
          terraform apply -auto-approve
      
      - name: Get deployment URL
        run: |
          echo "Deployment URL: $(terraform output -raw application_url)"
```

### AWS CloudFormation Template
```yaml
# cloudformation/fogis-stack.yml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'FOGIS Cloud Deployment Stack'

Parameters:
  Environment:
    Type: String
    Default: staging
    AllowedValues: [staging, production]
  
  InstanceType:
    Type: String
    Default: t3.small
    Description: EC2 instance type for ECS tasks

Resources:
  # VPC and Networking
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub 'fogis-vpc-${Environment}'
  
  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub 'fogis-cluster-${Environment}'
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 4
  
  # Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub 'fogis-alb-${Environment}'
      Scheme: internet-facing
      Type: application
      Subnets: 
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref ALBSecurityGroup

Outputs:
  ApplicationURL:
    Description: 'FOGIS Application URL'
    Value: !Sub 'https://${ApplicationLoadBalancer.DNSName}'
    Export:
      Name: !Sub '${AWS::StackName}-ApplicationURL'
  
  ClusterName:
    Description: 'ECS Cluster Name'
    Value: !Ref ECSCluster
    Export:
      Name: !Sub '${AWS::StackName}-ClusterName'
```

### Docker Compose for Cloud
```yaml
# docker-compose.cloud.yml
version: '3.8'

services:
  fogis-api-client:
    image: ${DOCKER_REGISTRY}/fogis-api-client:${VERSION}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - LOG_LEVEL=INFO
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  match-list-processor:
    image: ${DOCKER_REGISTRY}/match-list-processor:${VERSION}
    environment:
      - API_CLIENT_URL=http://fogis-api-client:8080
      - QUEUE_URL=${QUEUE_URL}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    depends_on:
      - fogis-api-client
  
  # Cloud-native services
  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
    volumes:
      - redis_data:/data
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
    depends_on:
      - fogis-api-client

volumes:
  redis_data:

networks:
  default:
    driver: overlay
    attachable: true
```

### AWS Cost Calculator
```python
# scripts/cost_calculator.py
class AWSCostCalculator:
    def __init__(self, region='us-east-1'):
        self.region = region
        self.pricing = {
            'fargate_cpu': 0.04048,  # per vCPU per hour
            'fargate_memory': 0.004445,  # per GB per hour
            'alb': 0.0225,  # per hour
            'rds_t3_micro': 0.017,  # per hour
            'ebs_gp2': 0.10,  # per GB per month
        }
    
    def calculate_monthly_cost(self, config):
        hours_per_month = 24 * 30
        
        # Fargate costs
        fargate_cost = (
            config['cpu_units'] * self.pricing['fargate_cpu'] +
            config['memory_gb'] * self.pricing['fargate_memory']
        ) * hours_per_month * config['replicas']
        
        # Load balancer
        alb_cost = self.pricing['alb'] * hours_per_month
        
        # Database
        db_cost = self.pricing['rds_t3_micro'] * hours_per_month
        
        # Storage
        storage_cost = config['storage_gb'] * self.pricing['ebs_gp2']
        
        total = fargate_cost + alb_cost + db_cost + storage_cost
        
        return {
            'fargate': fargate_cost,
            'load_balancer': alb_cost,
            'database': db_cost,
            'storage': storage_cost,
            'total': total
        }

# Example usage
calculator = AWSCostCalculator()
config = {
    'cpu_units': 1.0,  # 1 vCPU
    'memory_gb': 2.0,  # 2 GB RAM
    'replicas': 2,     # 2 instances
    'storage_gb': 20   # 20 GB storage
}

costs = calculator.calculate_monthly_cost(config)
print(f"Estimated monthly cost: ${costs['total']:.2f}")
```

### Auto-Scaling Configuration
```yaml
# Auto-scaling based on metrics
auto_scaling:
  target_cpu_utilization: 70
  target_memory_utilization: 80
  min_replicas: 1
  max_replicas: 10
  scale_up_cooldown: 300s
  scale_down_cooldown: 600s
  
  custom_metrics:
    - name: "matches_per_minute"
      target_value: 100
      scale_up_threshold: 150
      scale_down_threshold: 50
    
    - name: "queue_length"
      target_value: 10
      scale_up_threshold: 20
      scale_down_threshold: 5

scheduled_scaling:
  # Scale down during low usage hours
  - schedule: "0 22 * * *"  # 10 PM
    min_replicas: 1
    max_replicas: 2
  
  # Scale up during peak hours
  - schedule: "0 8 * * *"   # 8 AM
    min_replicas: 2
    max_replicas: 10
```

### CLI Deployment
```bash
# Install deployment CLI
npm install -g @fogis/cloud-deploy

# Deploy to AWS
fogis-deploy aws \
  --region us-east-1 \
  --environment production \
  --auto-scaling \
  --ssl-certificate arn:aws:acm:us-east-1:123456789:certificate/abc123

# Deploy to Google Cloud
fogis-deploy gcp \
  --project my-project \
  --region us-central1 \
  --min-instances 1 \
  --max-instances 10

# Deploy to DigitalOcean
fogis-deploy digitalocean \
  --app-name fogis-production \
  --region nyc1 \
  --size basic-xxs

# Check deployment status
fogis-deploy status --deployment-id abc123

# Scale deployment
fogis-deploy scale --replicas 5 --deployment-id abc123

# Get deployment logs
fogis-deploy logs --deployment-id abc123 --service api-client
```

### Web Deployment Interface
```html
<!-- Deployment wizard interface -->
<div class="deployment-wizard">
  <h1>Deploy FOGIS to the Cloud</h1>
  
  <div class="provider-selection">
    <h2>Choose Cloud Provider</h2>
    <div class="provider-cards">
      <div class="provider-card" data-provider="aws">
        <img src="aws-logo.png" alt="AWS">
        <h3>Amazon Web Services</h3>
        <p>Estimated cost: $45/month</p>
        <button>Deploy to AWS</button>
      </div>
      
      <div class="provider-card" data-provider="gcp">
        <img src="gcp-logo.png" alt="Google Cloud">
        <h3>Google Cloud Platform</h3>
        <p>Estimated cost: $38/month</p>
        <button>Deploy to GCP</button>
      </div>
      
      <div class="provider-card" data-provider="azure">
        <img src="azure-logo.png" alt="Azure">
        <h3>Microsoft Azure</h3>
        <p>Estimated cost: $42/month</p>
        <button>Deploy to Azure</button>
      </div>
    </div>
  </div>
  
  <div class="configuration-form">
    <h2>Configuration</h2>
    <form id="deployment-config">
      <label>Environment Name:</label>
      <input type="text" name="environment" value="production">
      
      <label>Region:</label>
      <select name="region">
        <option value="us-east-1">US East (Virginia)</option>
        <option value="us-west-2">US West (Oregon)</option>
        <option value="eu-west-1">Europe (Ireland)</option>
      </select>
      
      <label>Instance Size:</label>
      <select name="instance_size">
        <option value="small">Small (1 CPU, 2GB RAM) - $35/month</option>
        <option value="medium">Medium (2 CPU, 4GB RAM) - $70/month</option>
        <option value="large">Large (4 CPU, 8GB RAM) - $140/month</option>
      </select>
      
      <label>
        <input type="checkbox" name="auto_scaling" checked>
        Enable auto-scaling
      </label>
      
      <label>
        <input type="checkbox" name="ssl_certificate">
        Provision SSL certificate
      </label>
      
      <button type="submit">Deploy Now</button>
    </form>
  </div>
</div>
```

## 🧪 Testing Requirements
- [ ] **Multi-Cloud Testing** - Verify deployments work on all supported providers
- [ ] **Cost Validation** - Verify cost estimates are accurate
- [ ] **Auto-Scaling Testing** - Test scaling up and down scenarios
- [ ] **Disaster Recovery** - Test backup and restore procedures
- [ ] **Performance Testing** - Verify cloud deployments meet performance requirements
- [ ] **Security Testing** - Validate cloud security configurations

## 📊 Success Metrics
- <10 minute deployment time from start to running system
- 99.9% deployment success rate
- <$50/month cost for typical deployment
- 95% user satisfaction with cloud deployment experience
- Zero manual infrastructure management required

## 🔗 Dependencies
- Pre-built Docker images (Issue #4)
- Enhanced monitoring (Issue #6) for cloud metrics
- Auto-update system (Issue #5) for cloud deployments
- Credential management (Issue #3) for cloud credentials

### Multi-Region Deployment
```yaml
# Deploy across multiple regions for high availability
multi_region_config:
  primary_region: us-east-1
  secondary_regions:
    - us-west-2
    - eu-west-1
  
  failover:
    enabled: true
    health_check_interval: 30s
    failover_threshold: 3
  
  data_replication:
    strategy: async
    lag_tolerance: 5s
```

### Managed Service Integration
```yaml
# Use cloud-native managed services
managed_services:
  database:
    aws: rds-postgres
    gcp: cloud-sql
    azure: azure-database-postgresql
  
  cache:
    aws: elasticache-redis
    gcp: memorystore
    azure: azure-cache-redis
  
  queue:
    aws: sqs
    gcp: cloud-tasks
    azure: service-bus
  
  storage:
    aws: s3
    gcp: cloud-storage
    azure: blob-storage
```

### Cost Optimization Automation
```python
# Automated cost optimization
class CostOptimizer:
    def analyze_usage(self, deployment_id):
        """Analyze resource usage patterns"""
        metrics = self.get_metrics(deployment_id)
        recommendations = []
        
        # Check for over-provisioned resources
        if metrics['avg_cpu'] < 30:
            recommendations.append({
                'type': 'downsize',
                'resource': 'compute',
                'savings': '$15/month'
            })
        
        # Check for unused resources
        if metrics['avg_requests'] < 100:
            recommendations.append({
                'type': 'schedule_shutdown',
                'resource': 'non_production',
                'savings': '$25/month'
            })
        
        return recommendations
    
    def apply_optimizations(self, deployment_id, optimizations):
        """Apply cost optimizations automatically"""
        for opt in optimizations:
            if opt['type'] == 'downsize':
                self.resize_instances(deployment_id, opt['new_size'])
            elif opt['type'] == 'schedule_shutdown':
                self.setup_shutdown_schedule(deployment_id, opt['schedule'])
```

---
**Priority**: 🔥 MEDIUM - Expands deployment options significantly
**Effort**: 📊 VERY HIGH - 3-4 weeks development
**Impact**: 🚀 VERY HIGH - Eliminates local infrastructure requirements
